#!/bin/bash

# Get the verbs for a particular resource type. 
# Examples: 
# - get verbs for configmaps: kubectl verbs configmaps 
# - get verbs for deployments: kubectl verbs deployments apps
# (the second argument is required only for non-core resources)
# Install: 
#   curl -sL https://github.com/schollii/my-devops-lab/archive/refs/heads/main.zip --output /tmp/schollii.zip
#   unzip -p  /tmp/schollii.zip my-devops-lab-main/kubernetes/kubectl-verbs > /tmp/kubectl-verbs
#   sudo install /tmp/kubectl-verbs /usr/local/bin (or just chmod +x kubectl-verbs then move it to somewhere on your path)
# Run: 
#   in one terminal, start the k8s proxy for API server: kubectl proxy --port 8080
#   in another terminal, run kubectl verbs ...args... per examples

resourceName=$1
groupName=${2:-}

if [[ -z $groupName ]]; then
  curl -s http://localhost:8080/api/v1 | jq '.resources[] | [.name, (.verbs | join(" "))] | join(" = ")' -r | grep ^$resourceName
else
  api=$( curl -s http://localhost:8080/apis | jq '.groups[].preferredVersion.groupVersion' -r | grep ^$groupName )
  curl -s http://localhost:8080/apis/$api | jq '.resources[] | [.name, (.verbs | join(" "))] | join(" = ")' -r | grep ^$resourceName
fi
